import { User } from '@/lib/types';

export const mockUsers: User[] = [
  {
    id: '1',
    nim: '2021001001',
    name: 'Ahmad Fadhillah Ramadhan',
    email: 'ahmad.fadhillah@itbriau.ac.id',
    role: 'pimpinan',
    komisi: 'Pimpinan',
    jabatan: 'Ketua DPM',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Ahmad',
    phone: '081234567890',
    angkatan: '2021',
    prodi: 'Teknik Informatika',
  },
  {
    id: '2',
    nim: '2021001002',
    name: 'Siti Rahayu Pratiwi',
    email: 'siti.rahayu@itbriau.ac.id',
    role: 'pimpinan',
    komisi: 'Pimpinan',
    jabatan: 'Wakil Ketua DPM',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Siti',
    phone: '081234567891',
    angkatan: '2021',
    prodi: 'Teknik Sipil',
  },
  {
    id: '3',
    nim: '2021002001',
    name: 'Budi Santoso',
    email: 'budi.santoso@itbriau.ac.id',
    role: 'ketua_komisi',
    komisi: 'Komisi I',
    jabatan: 'Ketua Komisi I (Hukum & Legislasi)',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Budi',
    phone: '081234567892',
    angkatan: '2021',
    prodi: 'Teknik Elektro',
  },
  {
    id: '4',
    nim: '2021003001',
    name: 'Dewi Anggraeni',
    email: 'dewi.anggraeni@itbriau.ac.id',
    role: 'ketua_komisi',
    komisi: 'Komisi II',
    jabatan: 'Ketua Komisi II (Anggaran & Pengawasan)',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Dewi',
    phone: '081234567893',
    angkatan: '2021',
    prodi: 'Teknik Mesin',
  },
  {
    id: '5',
    nim: '2022001001',
    name: 'Rizki Maulana',
    email: 'rizki.maulana@itbriau.ac.id',
    role: 'anggota',
    komisi: 'Komisi I',
    jabatan: 'Anggota Komisi I',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Rizki',
    phone: '081234567894',
    angkatan: '2022',
    prodi: 'Teknik Informatika',
  },
  {
    id: '6',
    nim: '2022002001',
    name: 'Nur Hasanah',
    email: 'nur.hasanah@itbriau.ac.id',
    role: 'anggota',
    komisi: 'Komisi II',
    jabatan: 'Anggota Komisi II',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Nur',
    phone: '081234567895',
    angkatan: '2022',
    prodi: 'Teknik Kimia',
  },
  {
    id: '7',
    nim: '2022003001',
    name: 'Fajar Setiawan',
    email: 'fajar.setiawan@itbriau.ac.id',
    role: 'anggota',
    komisi: 'Komisi III',
    jabatan: 'Anggota Komisi III',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Fajar',
    phone: '081234567896',
    angkatan: '2022',
    prodi: 'Teknik Lingkungan',
  },
  {
    id: '8',
    nim: '2022004001',
    name: 'Indah Permata Sari',
    email: 'indah.permata@itbriau.ac.id',
    role: 'anggota',
    komisi: 'Komisi III',
    jabatan: 'Ketua Komisi III (Aspirasi & Kemahasiswaan)',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Indah',
    phone: '081234567897',
    angkatan: '2022',
    prodi: 'Teknik Industri',
  },
];


export function getUserById(id: string): User | undefined {
  return mockUsers.find((u) => u.id === id);
}

export function getUserByNim(nim: string): User | undefined {
  return mockUsers.find((u) => u.nim === nim);
}
